project_id: '493733'
api_token_env: 'CROWDIN_TOKEN'
preserve_hierarchy: true
files: [
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%osx_locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    },
  ]
