project_id: 7
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://chia.crowdin.com"
preserve_hierarchy: true
files: [
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%osx_locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    },
  ]
